/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

/**
 *
 * @author Diefo
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonPanel = new javax.swing.JPanel();
        picurenine = new javax.swing.JButton();
        picurethree = new javax.swing.JButton();
        picuretwo = new javax.swing.JButton();
        picuresix = new javax.swing.JButton();
        picurefive = new javax.swing.JButton();
        picureeight = new javax.swing.JButton();
        picurefour = new javax.swing.JButton();
        picureone = new javax.swing.JButton();
        picureseven = new javax.swing.JButton();
        PlayerChange = new javax.swing.JPanel();
        spielerX = new javax.swing.JLabel();
        tNameO = new javax.swing.JTextField();
        SpielerO = new javax.swing.JLabel();
        tNameX = new javax.swing.JTextField();
        Optionpannel = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnAbbruch = new javax.swing.JButton();
        statusText = new javax.swing.JPanel();
        status = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        statusXPanel = new javax.swing.JPanel();
        statusSpielerX = new javax.swing.JLabel();
        spielernameX = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        statusSiegeX = new javax.swing.JLabel();
        StatusOPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        spielernameO = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        statusSiegeO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        picurenine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/b9.jpg"))); // NOI18N
        picurenine.setText("Picture nine");
        picurenine.setActionCommand("P9");
        picurenine.setMaximumSize(new java.awt.Dimension(73, 73));

        picurethree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/b3.jpg"))); // NOI18N
        picurethree.setText("Picture three");
        picurethree.setActionCommand("P3");
        picurethree.setMaximumSize(new java.awt.Dimension(73, 73));

        picuretwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/b2.jpg"))); // NOI18N
        picuretwo.setText("Picture two");
        picuretwo.setActionCommand("P2");
        picuretwo.setMaximumSize(new java.awt.Dimension(73, 73));

        picuresix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/b6.jpg"))); // NOI18N
        picuresix.setText("Picture six");
        picuresix.setActionCommand("P6");
        picuresix.setMaximumSize(new java.awt.Dimension(73, 73));

        picurefive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/b5.jpg"))); // NOI18N
        picurefive.setText("Picture five");
        picurefive.setActionCommand("P5");
        picurefive.setMaximumSize(new java.awt.Dimension(73, 73));

        picureeight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/b8.jpg"))); // NOI18N
        picureeight.setText("Picture eight");
        picureeight.setActionCommand("P8");
        picureeight.setMaximumSize(new java.awt.Dimension(73, 73));

        picurefour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/b4.jpg"))); // NOI18N
        picurefour.setText("Picture four");
        picurefour.setActionCommand("P4");
        picurefour.setMaximumSize(new java.awt.Dimension(73, 73));

        picureone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/b1.jpg"))); // NOI18N
        picureone.setActionCommand("P1");
        picureone.setMaximumSize(new java.awt.Dimension(73, 73));

        picureseven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/b7.jpg"))); // NOI18N
        picureseven.setText("Picture seven");
        picureseven.setActionCommand("P7");
        picureseven.setMaximumSize(new java.awt.Dimension(73, 73));

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(picureone, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(picurefour, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(picureseven, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ButtonPanelLayout.createSequentialGroup()
                        .addComponent(picureeight, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(picurenine, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(ButtonPanelLayout.createSequentialGroup()
                        .addComponent(picurefive, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(picuresix, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ButtonPanelLayout.createSequentialGroup()
                        .addComponent(picuretwo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(picurethree, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(picureone, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(picuretwo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(picurethree, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(picurefour, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(picurefive, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(picuresix, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(picureseven, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(picureeight, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(picurenine, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        spielerX.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        spielerX.setText("Spieler X : ");
        spielerX.setIconTextGap(8);

        tNameO.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 11)); // NOI18N
        tNameO.setForeground(new java.awt.Color(255, 64, 64));
        tNameO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNameOActionPerformed(evt);
            }
        });

        SpielerO.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        SpielerO.setText("Spieler O : ");
        SpielerO.setIconTextGap(8);

        tNameX.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 11)); // NOI18N
        tNameX.setForeground(new java.awt.Color(255, 64, 64));
        tNameX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNameXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PlayerChangeLayout = new javax.swing.GroupLayout(PlayerChange);
        PlayerChange.setLayout(PlayerChangeLayout);
        PlayerChangeLayout.setHorizontalGroup(
            PlayerChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerChangeLayout.createSequentialGroup()
                .addGroup(PlayerChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlayerChangeLayout.createSequentialGroup()
                        .addComponent(spielerX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNameX, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PlayerChangeLayout.createSequentialGroup()
                        .addComponent(SpielerO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNameO, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PlayerChangeLayout.setVerticalGroup(
            PlayerChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerChangeLayout.createSequentialGroup()
                .addGroup(PlayerChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spielerX)
                    .addComponent(tNameX, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PlayerChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpielerO)
                    .addComponent(tNameO, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");

        btnAbbruch.setText("Abbruch");

        javax.swing.GroupLayout OptionpannelLayout = new javax.swing.GroupLayout(Optionpannel);
        Optionpannel.setLayout(OptionpannelLayout);
        OptionpannelLayout.setHorizontalGroup(
            OptionpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionpannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbbruch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset))
        );
        OptionpannelLayout.setVerticalGroup(
            OptionpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnStart)
                .addComponent(btnReset)
                .addComponent(btnAbbruch))
        );

        status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        status.setText("Status:");

        jLabel4.setBackground(new java.awt.Color(60, 240, 240));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("###");

        statusSpielerX.setText("Spieler X:");

        spielernameX.setText("###");

        jLabel6.setText("Siege:");

        statusSiegeX.setText("0");

        javax.swing.GroupLayout statusXPanelLayout = new javax.swing.GroupLayout(statusXPanel);
        statusXPanel.setLayout(statusXPanelLayout);
        statusXPanelLayout.setHorizontalGroup(
            statusXPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusXPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusSpielerX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spielernameX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusSiegeX)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        statusXPanelLayout.setVerticalGroup(
            statusXPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statusXPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusXPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusSpielerX)
                    .addComponent(spielernameX)
                    .addComponent(jLabel6)
                    .addComponent(statusSiegeX))
                .addGap(118, 118, 118))
        );

        jLabel8.setText("Spieler O:");

        spielernameO.setText("###");

        jLabel9.setText("Siege:");

        statusSiegeO.setText("0");

        javax.swing.GroupLayout StatusOPanelLayout = new javax.swing.GroupLayout(StatusOPanel);
        StatusOPanel.setLayout(StatusOPanelLayout);
        StatusOPanelLayout.setHorizontalGroup(
            StatusOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusOPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spielernameO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusSiegeO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StatusOPanelLayout.setVerticalGroup(
            StatusOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatusOPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(StatusOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(spielernameO)
                    .addComponent(jLabel9)
                    .addComponent(statusSiegeO))
                .addContainerGap())
        );

        javax.swing.GroupLayout statusTextLayout = new javax.swing.GroupLayout(statusText);
        statusText.setLayout(statusTextLayout);
        statusTextLayout.setHorizontalGroup(
            statusTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusTextLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusXPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(statusTextLayout.createSequentialGroup()
                        .addComponent(status)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addComponent(StatusOPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        statusTextLayout.setVerticalGroup(
            statusTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusTextLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statusTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addComponent(statusXPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatusOPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PlayerChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Optionpannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(79, 79, 79))
                    .addComponent(statusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(PlayerChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(Optionpannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(statusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tNameOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNameOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNameOActionPerformed

    private void tNameXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNameXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNameXActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel Optionpannel;
    private javax.swing.JPanel PlayerChange;
    private javax.swing.JLabel SpielerO;
    private javax.swing.JPanel StatusOPanel;
    private javax.swing.JButton btnAbbruch;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton picureeight;
    private javax.swing.JButton picurefive;
    private javax.swing.JButton picurefour;
    private javax.swing.JButton picurenine;
    private javax.swing.JButton picureone;
    private javax.swing.JButton picureseven;
    private javax.swing.JButton picuresix;
    private javax.swing.JButton picurethree;
    private javax.swing.JButton picuretwo;
    private javax.swing.JLabel spielerX;
    private javax.swing.JLabel spielernameO;
    private javax.swing.JLabel spielernameX;
    private javax.swing.JLabel status;
    private javax.swing.JLabel statusSiegeO;
    private javax.swing.JLabel statusSiegeX;
    private javax.swing.JLabel statusSpielerX;
    private javax.swing.JPanel statusText;
    private javax.swing.JPanel statusXPanel;
    private javax.swing.JTextField tNameO;
    private javax.swing.JTextField tNameX;
    // End of variables declaration//GEN-END:variables
}
